/* Code Map: setup.Apply orchestrator
 * - Apply: writes state.json + config.yaml in one call
 * - configPath: $XDG_CONFIG_HOME/voces/config.yaml (HOME fallback)
 * - buildConfigDoc: assembles YAML body, calls preserve* helpers
 *
 * CID Index:
 * CID:setup-apply-001 -> Apply
 * CID:setup-apply-002 -> configPath
 * CID:setup-apply-003 -> buildConfigDoc
 *
 * Quick lookup: rg -n "CID:setup-apply-" internal/setup/apply.go
 */
package setup

import (
	"fmt"
	"os"
	"path/filepath"

	"go.yaml.in/yaml/v3"
)

// CID:setup-apply-001 - Apply
// Purpose: persist the wizard result to disk (state.json first,
// then config.yaml). Single entry point for the wizard's commit
// step.
// Uses: Save (state), defaultConfigFor, preserveBinaryPath,
// preserveHotkeys, preserveModel, loadConfigRaw, configPath.
// Used by: cmd/voces/main.go (wizard commit step), test suite.

// Apply persists the wizard result to disk. Writes state.json
// (atomic .tmp + rename) and a fresh config.yaml with model paths
// derived from the state and engine binary paths from
// paths.EnginesDir(). Pre-existing user-set binary paths,
// secondary hotkey fields, and (rc1-hotpatch-24) the previously
// chosen whisper model are preserved (IMPL §3 Phase 5 contract).
//
// manifest may be nil; Apply falls back to DefaultManifest so
// preserveModel still has a manifest to validate against.
//
// State.json is written first so a partial failure leaves a
// recoverable record of what the user picked, even if config.yaml
// write fails.
func Apply(s *State, manifest *Manifest) error {
	if s == nil {
		return fmt.Errorf("Apply: state is nil")
	}
	if manifest == nil {
		manifest = DefaultManifest()
	}
	if err := Save(s); err != nil {
		return fmt.Errorf("Apply: save state: %w", err)
	}
	cfgPath, err := configPath()
	if err != nil {
		return fmt.Errorf("Apply: resolve config path: %w", err)
	}
	if err := os.MkdirAll(filepath.Dir(cfgPath), 0o755); err != nil {
		return fmt.Errorf("Apply: ensure config dir: %w", err)
	}
	doc, err := buildConfigDoc(s, cfgPath, manifest)
	if err != nil {
		return fmt.Errorf("Apply: build config: %w", err)
	}
	return os.WriteFile(cfgPath, doc, 0o644)
}

// CID:setup-apply-002 - configPath
// Purpose: resolve the canonical config.yaml path under
// $XDG_CONFIG_HOME/voces. The single source of truth for the
// on-disk path.
// Uses: os.Getenv.
// Used by: Apply, buildConfigDoc.

// configPath returns the canonical config.yaml path under
// $XDG_CONFIG_HOME/voces. Falls back to ~/.config/voces when
// XDG_CONFIG_HOME is unset.
func configPath() (string, error) {
	if v := os.Getenv("XDG_CONFIG_HOME"); v != "" {
		return filepath.Join(v, "voces", "config.yaml"), nil
	}
	return filepath.Join(os.Getenv("HOME"), ".config", "voces", "config.yaml"), nil
}

// CID:setup-apply-003 - buildConfigDoc
// Purpose: assemble the YAML body. Bridges defaults.go and
// preserve.go — generates the wizard's defaults, then layers
// pre-existing user values on top.
// Uses: defaultConfigFor, preserveBinaryPath, preserveHotkeys,
// preserveModel (rc1-hotpatch-24), loadConfigRaw, yaml.Marshal.
// Used by: Apply.

// buildConfigDoc assembles the YAML body. Loads the pre-existing
// file (if any) so user-set binary paths, secondary hotkey
// fields, and the previously chosen whisper model are preserved.
// manifest is threaded through so preserveModel can validate the
// pre-existing basename against the shipped model set.
func buildConfigDoc(s *State, cfgPath string, manifest *Manifest) ([]byte, error) {
	cfg := defaultConfigFor(s)
	if existing, err := loadConfigRaw(cfgPath); err == nil {
		preserveBinaryPath(&cfg, existing)
		preserveHotkeys(&cfg, existing)
		preserveModel(&cfg, existing, manifest)
	}
	out, err := yaml.Marshal(cfg)
	if err != nil {
		return nil, err
	}
	return append([]byte("# Voces — generated by setup wizard\n"), out...), nil
}
